### ISSUE TITLE
qc login fails after fresh install

### ISSUE THREAD

**Issue by ebengtso** [jorgemanrubia/qc#2]
Hi, DO you have any ideas how to fix this?

sh-3.2# qc login
/Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/qc-0.6.2/lib/qc/command_runner.rb:35: syntax error, unexpected '.' (SyntaxError)
      quant_connect_proxy&.credentials
                           ^
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/qc-0.6.2/lib/qc.rb:8:in `block in <top (required)>'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/qc-0.6.2/lib/qc.rb:8:in `each'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/qc-0.6.2/lib/qc.rb:8:in `<top (required)>'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/qc-0.6.2/bin/qc:4:in `<top (required)>'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/bin/qc:23:in `load'
	from /Users/erik/.rvm/rubies/ruby-2.2.4/bin/qc:23:in `<main>'
sh-3.2#

**Comment by jorgemanrubia** [comment]
@ebengtso That is because you need to use Ruby >= 2.3. With RVM you can install a new ruby with:

```
rvm install 2.4.2
rvm use 2.4.2 --default # to change ruby to 2.4.2 globally in your system
```

I'll document this >=2.3 dependency in the readme

**Comment by ebengtso** [comment]
thanks for the quick reply

**Comment by ebengtso** [comment]
also required 

gem install awesome_print

**Comment by jorgemanrubia** [comment]
Thanks @ebengtso, It's something I need to fix. `awesome_print` shouldn't be required in any case.
