### ISSUE TITLE
have a list of files to exclude from uploading

### ISSUE THREAD

**Issue by ebengtso** [jorgemanrubia/qc#4]
some files such as AssemblyInfo.cs should be excluded from upload.

Let the user define which files to exclude

**Comment by jorgemanrubia** [comment]
Since version 0.6.4 it will ignore `AssemblyInfo.cs`. You can add more ignores files by editing `.qc/settings.yml`.

If you were using an earlier version, you can edit `.qc/settings.yml` and add this at the end:

```
ignored_files:
- AssemblyInfo.cs
```

Or just run `qc init` again.

Thanks for the suggestion @ebengtso!
